### PR TITLE
Removed 'constants.js'

### LINKED ISSUE #52: Remove constants.js file
This file [constants.js](https://github.com/gh-conf/rhof/blob/master/lib/constants.js) is not getting used anymore and we can get this removed.

### PR DESCRIPTION
**Pull request by Simba-97**
Removed 'constants.js' as we do not use it anymore.
This PR resolved #52.

### CODE REVIEW

**Comment by Simba-97** [comment]
@arshadkazmi42 create a PR for #52. Please review when available.

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
This looks good.

But we need to remove referneces of this file from `index.js` also

Remove these two lines
https://github.com/gh-conf/rhof/blob/master/lib/index.js#L1
https://github.com/gh-conf/rhof/blob/master/lib/index.js#L7

**Comment by Simba-97** [comment]
@arshadkazmi42 Yeah. I just saw the checks fail. Making changes for it immediately.

**Review by arshadkazmi42 — APPROVED** [review]
Looks good. Thank you :+1: 

Lets get this merged :tada:

**Pull request merged**
