### PR TITLE
formatter fixed!

### PR DESCRIPTION
**Pull request by pwnb0y**
#44

### CODE REVIEW

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
This is not the right fix.

The tests are still failing. You should run tests before creating PR.

I did some debugging on this and found the actual issue is in this library https://github.com/arshadkazmi42/strmat/issues/21 due to which its not working. I have created a issue there, once that is fixed this should automatically be fixed.

For now I think we can add a hacky solution for this.

You can remove these current changes and change line [Line#14](https://github.com/pwnb0y/rhof/blob/formatter-fix/lib/format-hof.js#L14) with below code

```
    hof = `${hof}${Strmat.format(GH_TEMPLATES['HOF_TEMPLATE'], {'username': contributors[i].login})}`;
    // This is a hack to replace multiple occurances of username
    // We can remove this once this issue is fixed https://github.com/arshadkazmi42/strmat/issues/21
    hof = Strmat.format(hof, {'username': contributors[i].login});
```

Run the tests to verify nothing is breaking.

**Comment by arshadkazmi42** [comment]
@pwnb0y Please ignore the previous comment. I have got the issue fixed in the base library.

Now we can just update the version of the library in package.json and update lock file.

You do the following

1. Revert all the changes you have done
2. Remove `package-lock.json`
3. Update `strmat` version to `1.1.0` at this line https://github.com/gh-conf/rhof/blob/master/package.json#L40
    Should be changed to this ` "strmat": "^1.1.0"`
4. Re-install node modules by running `npm install` to generate new package-lock.json
5. Commit all the changes and update the pull request.

**Comment by pwnb0y** [comment]
ok sure

**Review by arshadkazmi42 — APPROVED** [review]
Looks Good :+1:

**Pull request merged**
